#187 и #159
heritagemap/frontend-pwa pull request #196
Opened 2020-12-09 15:00 UTC by Julia-Lavrova

2020-12-09 15:01 UTC, Julia-Lavrova commented
https://github.com/heritagemap/frontend-pwa/issues/159
https://github.com/heritagemap/frontend-pwa/issues/187

2020-12-09 15:15 UTC, avdeev requested changes

2020-12-09 15:15 UTC, avdeev commented on src/components/Map/index.tsx
> +      window.localStorage.setItem('viewport', updatedViewport);
можно тоже обернуть в `try/catch` и не проверять наличие `window?.localStorage`

вроде, в инкогнито могут быть проблемы с попыткой обратиться к `window?.localStorage`

можно проверить

на твой вкус

2020-12-09 15:15 UTC, avdeev commented on src/components/Map/index.tsx
> +        console.log(err);
я бы так сделал, чтобы красненькое было :)

на твой вкус

```suggestion
        console.error(err);
```

2020-12-09 15:15 UTC, avdeev commented on src/components/Map/index.tsx
> +        prevPosition = JSON.parse(window.localStorage.getItem('viewport') || '');
`JSON.parse('')` будет всегда падать, возможно правильнее 

```suggestion
        prevPosition = JSON.parse(window.localStorage.getItem('viewport') || '{}');
```

2020-12-09 15:21 UTC, Julia-Lavrova commented on src/components/Map/index.tsx
> +      window.localStorage.setItem('viewport', updatedViewport);
Это и сделано для инкогнито

2020-12-09 18:54 UTC, avdeev approved these changes
lgtm

2021-01-19 10:26 UTC, avdeev approved these changes

2021-01-19 11:54 UTC, merged